#Linguagem de build
language: python

#Versão do python
python: 
  - '3.8'

# Modulo do python
install:
  - pip install flask

# Defini o script de Teste que deve rodar toda vez que o código for alterado.                                                                                                                            
script:                                                                                                                                                                                                  
  - python -m unittest -v test

# Definir o Deploy no Heroku
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: devops-gallo